[project]
name = "backend"
version = "0.1.0"
description = "Backend dependencies"
readme = "README.md"
authors = [
    { name = "Johnny Hyytiäinen", email = "johnny.hyytiainen@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
